# Generated by Django 5.0.6 on 2024-08-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_product_product_dicount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
