# Generated by Django 5.0.6 on 2024-08-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
