# Generated by Django 5.0.6 on 2024-08-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_carts_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="carts",
            name="artical",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="carts",
            name="brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="carts",
            name="color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="carts",
            name="size",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
