# Generated by Django 5.0.6 on 2024-08-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_carts_artical_carts_brand_carts_color_carts_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carts",
            name="total",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
